spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
sentry.dsn=https://175df70cc551efc22dd25f4cc4c17ef7@o4508285839605760.ingest.de.sentry.io/4508691883622480
sentry.environment=local