spring.datasource.url=jdbc:postgresql://127.0.0.1:5433/asa
spring.datasource.username=asa_user
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}


aws.eventBridge.bus=dummy-event-bus
aws.s3.bucket=dummy-bucket
aws.sqs.queue.url=dummy-queue-url
aws.region=eu-west-3
aws.ses.source=noreply@test.com

SENSITIVE_WORKERS_CODES=dummy
ACCOUNTANTS=${ACCOUNTANTS_EMAIL}
MAX_LATENESS_REPORT=4

asa.care.product.code=care
asa.paid.care.mission.codes=paidleave
asa.contract.alert.threshold=11

spring.security.oauth2.client.registration.casdoor.client-id=${CASDOOR_CLIENT_ID}
spring.security.oauth2.client.registration.casdoor.client-secret=${CASDOOR_CLIENT_SECRET}
spring.security.oauth2.client.provider.casdoor.authorization-uri=http://localhost:8000/login/oauth/authorize
spring.security.oauth2.client.provider.casdoor.token-uri=http://localhost:8000/api/login/oauth/access_token
spring.security.oauth2.client.provider.casdoor.jwk-set-uri=http://localhost:8000/.well-known/jwks
spring.security.oauth2.client.registration.casdoor.provider=casdoor
spring.security.oauth2.client.registration.casdoor.redirect-uri={baseUrl}/login/oauth2/code/casdoor
spring.security.oauth2.client.registration.casdoor.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.casdoor.scope=openid,profile,email
casdoor.logout.url=http://localhost:8000/logout
asa.logout.url=http://localhost:8000/logout

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
sentry.dsn=${SENTRY_DSN}
sentry.environment=local