spring.datasource.url=jdbc:postgresql://localhost:5432/asa
spring.datasource.username=postgres
spring.datasource.password=manda2102
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.flyway.enabled=false
spring.flyway.out-of-order=false

aws.s3.bucket=dev-bucket
aws.eventBridge.bus=dev-bus
aws.ses.source=noreply@poja.io

asa.care.product.code=PC
asa.paid.care.mission.codes=PC,MC
asa.logout.url=http://localhost:8080

server.error.include-message=always

casdoor.logout.url=http://localhost:8080

spring.security.oauth2.client.registration.casdoor.client-id=f4949f21c53aefe5a680
spring.security.oauth2.client.registration.casdoor.client-secret=2982243e95a88d225dd12347ac0d6af5f9a13a76
spring.security.oauth2.client.registration.casdoor.redirect-uri={baseUrl}/login/oauth2/code/casdoor
spring.security.oauth2.client.registration.casdoor.scope[0]=openid
spring.security.oauth2.client.registration.casdoor.scope[1]=profile
spring.security.oauth2.client.registration.casdoor.scope[2]=email
spring.security.oauth2.client.provider.casdoor.issuer-uri=http://localhost:8000
spring.security.oauth2.client.provider.casdoor.user-name-attribute=preferred_username

SENSITIVE_WORKERS_CODES=
ACCOUNTANTS=admin@hei.school
MAX_LATENESS_REPORT=999
