# Configuration existante
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
sentry.dsn=https://175df70cc551efc22dd25f4cc4c17ef7@o4508285839605760.ingest.de.sentry.io/4508691883622480
sentry.environment=local

# Configuration de la base de données
spring.datasource.url=jdbc:postgresql://ep-shiny-rice-a2injhw0-pooler.eu-central-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=sivousleakezcemotdepasseanouveau...69
spring.datasource.driver-class-name=org.postgresql.Driver
spring.flyway.out-of-order=true

# Configuration métier (depuis votre .env)
asa.care.product.code=CA
asa.logout.url=http://localhost:8080/
asa.paid.care.mission.codes=CA-ABP,CA-TB
aws.ses.source=dummy
cognito.logout.url=https://prod-hei-admin.auth.eu-west-3.amazoncognito.com/logout
server.error.include-message=always

# Configuration OAuth2 Cognito
spring.security.oauth2.client.provider.cognito.issuer-uri=https://cognito-idp.eu-west-3.amazonaws.com/eu-west-3_Sn2an38yu
spring.security.oauth2.client.provider.cognito.user-name-attribute=username
spring.security.oauth2.client.redirect-uri=http://localhost:8080/login/oauth2/code/{registrationId}
spring.security.oauth2.client.registration.cognito.client-id=7ada39jv90rrnr1lugm3a9op69
spring.security.oauth2.client.registration.cognito.client-secret=3khabvuvr0pkdcnm6o5n97h8hkefr79n8voal250e8k9b51p2k3
spring.security.oauth2.client.registration.cognito.scope=email,openid,phone